version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "crazy-max"
    default_labels:
      - ":game_die: dependencies"
      - ":robot: bot"
